### ISSUE TITLE
String Parsing Error

### ISSUE THREAD

**Issue by BookOwl** [StackLanguge/Stack-Language#15]
The latest version of Stack can not parse strings. The program `"F" print` gives the error `"F" is not defined as a variable or word!`

**Comment by BookOwl** [comment]
During debugging, I have found that the problem is in stack_parser.py
It is parsing strings as vars.

**Comment by BookOwl** [comment]
The problem is in `is_str()` in constants.py
It is returning `False` when it should be returning `True`

**Comment by BookOwl** [comment]
It turns out that I was using the wrong quotes. Oops...

**Comment by jeandrek** [comment]
Oh yeah you were using special matching quotes, right?
