### ISSUE TITLE
File access

### ISSUE THREAD

**Issue by BookOwl** [StackLanguge/Stack-Language#7]
We need to figure out what the interface for accessing files from Stack scripts should be.

**Comment by towerofnix** [comment]
`fwrite`, `fappend`, `fread`, `freadlines`, `freadbytes`?

**Comment by BookOwl** [comment]
We don't have a way to work with bytes with Stack.
For opening files, how about `'file1.txt' fopen`

**Comment by towerofnix** [comment]
`'file1.txt' fopen fread`?

**Comment by BookOwl** [comment]
Yes

**Comment by towerofnix** [comment]
What type of data is the result of `'file1.txt' fopen`?

**Comment by BookOwl** [comment]
A file type that supports the file operations.

**Comment by towerofnix** [comment]
Okay :package:

**Comment by BookOwl** [comment]
I'll implement it.

**Comment by towerofnix** [comment]
kthx.

:P Though if you take a look at my stdlib branch you can see I've already got importing python modules working!

You should check it out.

**Comment by BookOwl** [comment]
Awesome!

**Comment by towerofnix** [comment]
https://github.com/StackLanguge/stack-language/commit/720c74b10a6cbdd709ba0c2aeea95fad2489b89c

**Comment by jeandrek** [comment]
Wow importing Python modules!
Also can you do `1 fread` to read from STDIN?

**Comment by towerofnix** [comment]
Why `1`?

In theory you could do so, but you'd need to write a python script to get `sys.stdin`'s path. :package:

Also like a lot of things here #23

**Comment by BookOwl** [comment]
Implemented by #23

**Comment by jeandrek** [comment]
> Why `1`?

Because `1` is the file descriptor for STDIN.
(it may need casting or something though as it isn't a complete file object)

If not, you can still do `'/dev/tty' fopen` on UNIX-like systems. (but not windows)

**Comment by towerofnix** [comment]
Oh yes, that's true.

**Comment by jeandrek** [comment]
> Oh yes, that's true.

oh wait you can already do that with `'' input`
but you could use `fwrite` to write to stderr
